services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}
    networks:
      - docker_practice

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - docker_practice
    command: npm start  # <-- must use dev server for hot reload

  backend:
    container_name: backend
    platform: linux
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - GUNICORN_CMD_ARGS=-w 4 --threads 4 --worker-class=gthread -b 0.0.0.0:8000
      - RUNNING_IN_DOCKER=DO-NOT-CHANGE
    env_file:
      - .env
    networks:
      - docker_practice
volumes:
  postgres-data:
networks:
  docker_practice:
    driver: bridge
